### ISSUE TITLE
Map string to supported charmaps (Character analysis broken on unicode glyphs)

### ISSUE THREAD

**Issue by davelab6** [davelab6/pyfontaine#53]
- [x] when I try to input a string as the single argument to pyfontaine, it crashes on a unicode error which I guess should be fixed
```
$ pyfontaine "Zuótiān wǒ bāng nǚ’ér qù yī jiā chāoshì mǎi kělè, xīfàn, dòupí"
Traceback (most recent call last):
  File "/usr/local/bin/pyfontaine", line 4, in <module>
    __import__('pkg_resources').run_script('fontaine==1.2.2', 'pyfontaine')
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 534, in run_script
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources.py", line 1438, in run_script
  File "/usr/local/lib/python2.7/site-packages/fontaine-1.2.2-py2.7.egg/EGG-INFO/scripts/pyfontaine", line 300, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/fontaine-1.2.2-py2.7.egg/EGG-INFO/scripts/pyfontaine", line 200, in main
    print("'%s' is not found" % (filename))
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 351, in write
    data, consumed = self.encode(object, self.errors)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
$
```

- [x] I want to be able to input a string as the single argument to pyfontaine, to see which charmaps in all collections can support the string. Eg given that string `Adobe Latin 2` doesn't support it, but perhaps `Adobe Latin 5` does.

- [x] When this is ready, email Marjolein from the noto mailing list about it

**Comment by davelab6** [comment]
```
$ pyfontaine "Zuótiān wǒ bāng nǚ’ér qù yī jiā chāoshì mǎi kělè, xīfàn, dòupí"
Character Set                                                   
Extensis AdobeCyrillic1 + Cyrillic                                             
Extensis AdobeCyrillic2 + AdobeCyrillic1                                       
Extensis AdobeCyrillic3 + AdobeCyrillic2                                       
Extensis AdobeLatin2 + Latin                                                   
Extensis AdobeLatin3 + AdobeLatin2                                             
Extensis AdobeLatin4 + AdobeLatin3                                             
Extensis Afrikaans + English                                                   
Extensis ArabicLatinTransDIN + English                                         
Extensis ArabicLatinTransALA + English                                         
Extensis Baltic + English                                                      
Extensis Bulgarian + Cyrillic                                                  
Extensis CanadianSyllabics                                                     
Extensis Catalan + English                                                     
Extensis Cherokee                                                              
Extensis Coptic                                                                
Extensis Cyrillic + Russian                                                    
Extensis Czech + English                                                       
Extensis Danish + English                                                      
Extensis Dargin + Cyrillic                                                     
Extensis Dungan + Cyrillic                                                     
Extensis English                                                True           
Extensis Esperanto + English                                    True           
Extensis Estonian + English                                     True           
Extensis EuropeanCentral + English                              True           
Extensis EuropeanWestern                                                       
Extensis Even + Cyrillic                                                       
Extensis Evenk + Cyrillic                                                      
Extensis Filipino + English                                     True           
Extensis Finnish + English                                      True           
Extensis French + English                                       True           
Extensis Gagauz + Cyrillic                                                     
Extensis German + English                                       True           
Extensis GreekBasic                                                            
Extensis GreekPolytonic + GreekBasic                                           
Extensis Guarani + English                                      True           
Extensis Hausa + English                                        True           
Extensis Hawaiian + English                                     True           
Extensis Hebrew                                                                
Extensis Hungarian + English                                    True           
Extensis Icelandic + English                                    True           
Extensis Igbo + English                                         True           
Extensis IndicLatinTransHunt + English                          True           
Extensis IndicLatinTransIAST + English                          True           
Extensis Indonesian + English                                   True           
Extensis Ingush + Cyrillic                                                     
Extensis Irish + English                                        True           
Extensis Italian + English                                      True           
Extensis Kabardian + Cyrillic                                                  
Extensis Kalmyk + Cyrillic                                                     
Extensis KarakalpakCyrillic + Cyrillic                                         
Extensis KazakhCyrillic + Cyrillic                                             
Extensis Khakas + Cyrillic                                                     
Extensis Khanty + Cyrillic                                                     
Extensis Komi + Cyrillic                                                       
Extensis Koryak + Cyrillic                                                     
Extensis Kyrgyz + Cyrillic                                                     
Extensis Lakh + Cyrillic                                                       
Extensis Latin                                                                 
Extensis Latvian + English                                      True           
Extensis Lezgi + Cyrillic                                                      
Extensis Lithuanian + English                                   True           
Extensis MacRoman + English                                     True           
Extensis WinANSIPlusMacRoman + English                          True           
Extensis Malagasy + English                                     True           
Extensis Maltese + English                                      True           
Extensis Mansi + Cyrillic                                                      
Extensis MariHill + Cyrillic                                                   
Extensis MariMeadow + Cyrillic                                                 
Extensis MoldovanCyrillic + Cyrillic                                           
Extensis MongolianCyrillic + Cyrillic                                          
Extensis Nenets + Cyrillic                                                     
Extensis Nivkh + Cyrillic                                                      
Extensis NorwegianBokmål + English                              True           
Extensis NorwegianNynorsk + English                             True           
Extensis PanAfricanLatin + English                              True           
Extensis Ossetic + Cyrillic                                                    
Extensis Pinyin + English                                       True           
Extensis Polish + English                                       True           
Extensis Portuguese + English                                   True           
Extensis Romanian + English                                     True           
Extensis Russian                                                               
Extensis Serbo-CroatianCyrillic + Cyrillic                                     
Extensis Serbo-CroatianLatin + English                          True           
Extensis Slovak + English                                       True           
Extensis Spanish + English                                      True           
Extensis Swedish + English                                      True           
Extensis Slovene + English                                      True           
Extensis Tabasaran + Cyrillic                                                  
Extensis TatarLatin + English                                   True           
Extensis TatarCyrillic + Cyrillic                                              
Extensis Turkish + English                                      True           
Extensis TurkmenLatin + English                                 True           
Extensis Ukrainian + Cyrillic                                                  
Extensis Uzbek + Cyrillic                                                      
Extensis Vietnamese + English                                   True           
Extensis Welsh + English                                        True           
Extensis WinANSI + English                                      True           
Extensis Yakut + Cyrillic                                                      
Extensis Yup'ik + Cyrillic                                                     
Subset cyrillic-menu                                                           
Subset greek-menu                                                              
Subset latin-ext                                                               
Subset latin                                                                   
Subset vietnamese-menu                                                         
Unicode Block Basic Latin                                                      
Unicode Block Latin-1 Supplement                                               
Unicode Block Latin Extended-A                                                 
Unicode Block Latin Extended-B                                                 
Unicode Block General Punctuation                                              
Adobe Latin 1                                                                  
Adobe Latin 2                                                                  
Adobe Latin 3                                                                  
Adobe Latin 4                                                   True           
Adobe Latin 5                                                   True           
African                                                                        
Baltic                                                                         
Catalan                                                                        
Central European                                                               
Full Danish Alphabet                                                           
Full Finnish Alphabet                                                          
Google arabic                                                                  
Arimo cyrillic-ext+latin                                                       
Impallari latin-ext                                                            
Lato European                                                                  
Lato Vietnamese                                                                
Google latin-ext                                                               
Google latin                                                                   
Google vietnamese                                                              
Icelandic Accents                                                              
Pan African Latin                                                              
Polish Accents                                                                 
Full Polish Alphabet                                                           
Slovak Accents                                                                 
Full Slovak Alphabet                                                           
Western European 
```
