### ISSUE TITLE
error reading .ttc file

### ISSUE THREAD

**Issue by zxytim** [davelab6/pyfontaine#57]
when reading .ttc file:
```sh
$ pyfontaine simsun.ttc                                                                                              
Traceback (most recent call last):
  File "/home/zxytim/.local/bin/pyfontaine", line 266, in <module>
    main()
  File "/home/zxytim/.local/bin/pyfontaine", line 193, in main
    tree = director.construct_tree(fonts)
  File "/home/zxytim/.local/lib/python2.7/site-packages/fontaine/builder.py", line 118, in construct_tree
    font = FontFactory.openfont(font_filename, charmaps=self.charmaps)
  File "/home/zxytim/.local/lib/python2.7/site-packages/fontaine/font.py", line 124, in openfont
    return TTFont(fontfile, charmaps)
  File "/home/zxytim/.local/lib/python2.7/site-packages/fontaine/font.py", line 130, in __init__
    self._fontFace = FontFace(fontfile)
  File "/home/zxytim/.local/lib/python2.7/site-packages/fontaine/font.py", line 45, in __init__
    self.ttf = ttLib.TTFont(open(fontfile))
  File "/home/zxytim/.local/lib/python2.7/site-packages/FontTools/fontTools/ttLib/__init__.py", line 156, in __init__
    self.reader = sfnt.SFNTReader(file, checkChecksums, fontNumber=fontNumber)
  File "/home/zxytim/.local/lib/python2.7/site-packages/FontTools/fontTools/ttLib/sfnt.py", line 36, in __init__
    raise ttLib.TTLibError, "specify a font number between 0 and %d (inclusive)" % (self.numFonts - 1)
fontTools.ttLib.TTLibError: specify a font number between 0 and 1 (inclusive)
```
As I have a check at your code, I found the problem lies in that all fontaine.font.{FontFactory, TTFont, FontFace} does not handle fontNumber needed by fontTools.

**Comment by davelab6** [comment]
Thanks! @vitalyvolkov please resolve :)

**Comment by davelab6** [comment]
@zxytim can this be closed?
