### ISSUE TITLE
AttributeError: 'icu.Locale' object has no attribute 'lower'

### ISSUE THREAD

**Issue by davelab6** [davelab6/pyfontaine#58]
Error with newscycle:

```sh
$ bzr co lp:newscycle;
$ cd newscycle;
$ pyfontaine --set 'gwf_latin-ext' *ttf;
Traceback (most recent call last):
  File "/usr/local/bin/pyfontaine", line 4, in <module>
    __import__('pkg_resources').run_script('fontaine==1.3.0', 'pyfontaine')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 517, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources.py", line 1436, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg/EGG-INFO/scripts/pyfontaine", line 417, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg/EGG-INFO/scripts/pyfontaine", line 335, in main
    tree = director.construct_tree(fonts)
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg/fontaine/builder.py", line 141, in construct_tree
    for charmapinfo in font.get_orthographies(self.library):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/fontaine-1.3.0-py2.7.egg/fontaine/font.py", line 243, in get_orthographies
    elif abbr and abbr.lower() in self._charmaps:
AttributeError: 'icu.Locale' object has no attribute 'lower'
$
```

**Comment by davelab6** [comment]
ping @vitalyvolkov
