### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec

### ISSUE THREAD

**Issue by davelab6** [davelab6/pyfontaine#65]
```
$ git clone https://github.com/google/fonts.git;
$ pyfontaine --text-compact fonts/ofl/slabo27px/Slabo27px-Regular.ttf > slavo27px-compact.txt
WARNING: Please install PyICU <https://pypi.python.org/pypi/PyICU> to enable CLDR related features, perhaps with: pip install pyicu
Traceback (most recent call last):
  File "/usr/local/bin/pyfontaine", line 5, in <module>
    pkg_resources.run_script('fontaine==1.3.1', 'pyfontaine')
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources/__init__.py", line 723, in run_script
    
  File "build/bdist.macosx-10.9-x86_64/egg/pkg_resources/__init__.py", line 1636, in run_script
    
  File "/Library/Python/2.7/site-packages/fontaine-1.3.1-py2.7.egg/EGG-INFO/scripts/pyfontaine", line 420, in <module>
    main()
  File "/Library/Python/2.7/site-packages/fontaine-1.3.1-py2.7.egg/EGG-INFO/scripts/pyfontaine", line 239, in main
    Builder.compact_(fonts)
  File "/Library/Python/2.7/site-packages/fontaine-1.3.1-py2.7.egg/fontaine/builder.py", line 296, in compact_
    subset.common_name))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe5' in position 22: ordinal not in range(128)
```

**Comment by vitalyvolkov** [comment]
See commit https://github.com/davelab6/pyfontaine/commit/2f44359d719a20677635ac4245e52fefcdb3bf03#diff-b6191bf1fef17e5b32b18eaefe70d2beR296
