### ISSUE TITLE
"No module named fontTools.unicode" on Linux

### ISSUE THREAD

**Issue by dandv** [davelab6/pyfontaine#94]
How should one install pyfontaine on Linux? I have python 2.7.12 already and I've run `sudo pip install fontaine`. Not sure what to do about `icu4c` on a Linux system. Running pyfontaine fails with:

```
Traceback (most recent call last):
  File "/usr/local/bin/pyfontaine", line 26, in <module>
    from fontaine.builder import Builder, Director, CharMapGen, GlyphMapGen
  File "/usr/local/lib/python2.7/dist-packages/fontaine/builder.py", line 24, in <module>
    from fontaine.font import FontFactory, CharsetInfo
  File "/usr/local/lib/python2.7/dist-packages/fontaine/font.py", line 16, in <module>
    from fontTools.unicode import Unicode
ImportError: No module named fontTools.unicode
```

**Comment by dandv** [comment]
Had to `sudo pip install fonttools tabulate` on Linux. Maybe a short line with Linux installation instructions can be added?

**Comment by davelab6** [comment]
@dandv thanks for reporting; I updated README but the real fix will be to make a proper `requirements.txt` and pip package that has its pip dependencies sorted out. @felipesanches could help with this soon
